### ISSUE TITLE
What tool you use for the xserver?

### ISSUE THREAD

**Issue by camsn0w** [Xyene/wsl-dotfiles#2]

**Comment by Xyene** [comment]
I'm using VcXSrv with no issues, I've found it very stable and it had the greatest performance in 4K res from the servers I tried. I'm using a simple VBScript file to launch it, which I have pinned to my start menu:

```vbs
Set vcxsrvShell = CreateObject("WScript.Shell" ) 
vcxsrvShell.Run """C:\Program Files\VcXsrv\vcxsrv.exe"" -nodecoration -screen 0 3840x2160@1"	
Set vcxsrvShell = Nothing 

Set wslShell = CreateObject("WScript.Shell" ) 
wslShell.Run "bash -c ""/home/xyene/.scripts/wlaunch""", 0
Set wslShell = Nothing 

Set pulseShell = CreateObject("WScript.Shell")
pulseShell.Run """C:\tools\pulseaudio-1.1\bin\pulseaudio.exe""", 0
Set pulseShell = Nothing
```

`wlaunch` is in this repo, and pulseaudio is just there in case you also want sound.

**Comment by camsn0w** [comment]
I keep getting missing icons, just white squares that each have a red x.

**Comment by CatCassie** [comment]
Hello, 

Does it matter where I keep the .vbs script?
